services:
  web:
    image: ghcr.io/jigypeper/phase-alpha-site:latest
    container_name: pa-site
    ports:
      - "3000:3000"
    volumes:
      - .env:/app/.env
    environment:
      - RUST_LOG=info
      - LEPTOS_OUTPUT_NAME=phase-alpha-site
      - APP_ENVIRONMENT=production
      - LEPTOS_SITE_ADDR=0.0.0.0:3000
      - LEPTOS_SITE_ROOT=site
